### ISSUE TITLE
Docker ARM build

### ISSUE THREAD

**Issue by mitchplze** [spiral-project/ihatemoney#1066]
Hello. Would it be possible to publish and maintain an arm build of the Docker Hub image, so that it can be ran from a Raspberry Pi, etc.?

**Comment by almet** [comment]
cc @youegraillot

**Comment by mitchplze** [comment]
@almet From my understanding, the project team would just need to build the Docker image as normal, but on a machine running _aarch64_ architecture instead of _amd64_ (such as a Raspberry Pi or a number of cloud VMs). 

I was able to clone the Git repo to my Pi, run `docker build .` and eventually got the image built. As far as I can tell there's nothing in the Python build that is amd64-specific, so no functionality should technically be broken.

Unless I'm missing something entirely.

**Comment by greedybro** [comment]
Hi everyone !

I can confirm what @mitchplze said, there is nothing specific to any architecture in your Dockerfile.

And since you already use `docker/build-push-action@v2` in your CI, the build should be as simple as specifying platforms in the stage. Following this example -> https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images

i can open a PR, but i need to test that the build i did is usable. (https://hub.docker.com/r/greedybro/ihatemoney/tags)
