### ISSUE TITLE
Minimalist index page

### ISSUE THREAD

**Issue by astorije** [spiral-project/ihatemoney#108]
It would be nice to be able to disable the demo project, as well as the public ability to create new projects. This could be handled in `settings.py`.
I would love to implement this feature but I prefer to have the general opinion about this. Any suggestions?

**Comment by ametaireau** [comment]
So, if I understand correctly, the idea would be to only have one project, and disable the possibility to create new projects. Is this correct?

If yes, then I believe we should add new settings (`DISABLE_PROJECT_CREATION` and `DEFAULT_PROJECT_NAME`). and change the routing based on that, plus disable some endpoints depending on the settings.

@astorije do you still need this?

**Comment by almet** [comment]
Gentle bump on this. Anyone would like to volunteer on this?

**Comment by astorije** [comment]
Hi @almet! Sorry, there is an extremely low chance I'd be working on this in any foreseeable future as I'm already involved in way more projects than I can handle at the moment.
Anyone willing to contribute, I'd be happy to discuss/add details/give 2c if that's any useful.

Feel free to close this if you think it's not a reasonable idea anymore.

**Comment by 0livd** [comment]
I'd like to work on this one but I'm not really sure of the implementation. In my opinion the main issue is that if you host ihatemoney on a public server, anyone can create new projects and manage their expenses on your instance. As @astorije said, this could be solved by adding a new parameter in settings.py so that new project creation will require a password (also specified in settings.py). It could also automatically disable the demo project. What do you guys think ?

**Comment by 0livd** [comment]
I made a WIP commit to show how i would implement it. This adds 2 new settings, PUBLIC_SERVER and PUBLIC_SERVER_PASSWORD. When PUBLIC_SERVER is set to True, the server password must be provided to create a new project and the demo project is no longer a special project.
Here PUBLIC_SERVER is set to True for the example but it should set to False by default.
Tests are broken in this commit
Any comment on this ?

**Comment by almet** [comment]
Hi, thanks for taking the time to work on this, I believe it will be useful to others :)

Here are a few comments:

I find the name "public server" unclear. A name like "AUTHORIZE_PROJECT_CREATION" seems to better  explain what the intent is.

to be honest, I'm not so clear about what we are trying to achieve exactly here. If we want to have a way for the administrator to control the creation of new projects, I see different options in order to accomplish just this:

- Have an email sent to the administrator when a new project is created, and having him validate them manually;
- Have an "administration" dashboard where it is possible for the administrator to perform administrative tasks (this might be handy for #42 as well), and add the ability to create new projects there;
- Have the ability for anyone with a passcode to create a new project (what you're proposing here).

I like option 2 and option 3, and they try to accomplish slightly different things. I would be interested to get the inputs of other members of the projects on this. @astorije: do you have thoughts about how you would like to see this implemented? @JocelynDelalande what do you think? Any input about the UX would also be helpful @QuentinRoy :)

Again, thanks for your proposition and code!

**Comment by almet** [comment]
Gentle bump on the topic.

If anyone got ideas about which direction we should take, dont hesitate to comment so we can go further on this. Thanks !

**Comment by Phyks** [comment]
For my personal use case, the following features would be awesome:

* Having a setting to completely disable the demo.
* Having a setting to prevent creation of other projects.

This would mean an instance would then be "private".

Additionnally, there could be some "admin page" to list all the available projects on the instance, monitor them etc (with some special admin password, hashed in the settings) and from this page one could create a new project even if the creation is disabled.

**Comment by 0livd** [comment]
@Phyks Thanks for your input, we have pretty much the same use case
I would divide this into 2 PRs:

- Enhance the existing dashboard page to make it an admin dashboard with features like project creation/deletion and others stated in #42 . A password is required to access it
- Add a new setting to disable the demo and project creation from the home page (project creation is available on the admin dashboard in any case)

**Comment by almet** [comment]
That sounds something simple enough to me, if anyone wants to give it a go, please do and I will review, comment and it will eventually make it to master :)

**Comment by Phyks** [comment]
Isn't this done in recent commits? At least, the HEAD commit looks a lot like what I was looking for in https://github.com/spiral-project/ihatemoney/issues/108#issuecomment-293271142 :)

**Comment by 0livd** [comment]
yep it's done but not documented yet... see #212

**Comment by Phyks** [comment]
Ok, so this issue may be closed in favor of #212?

Not sure if settings should actually be commented somewhere on the wiki, or just commented in the `default_settings.py` file. I think the latter might be enough and ease the maintenance of up to date comments.

**Comment by almet** [comment]
Hi, in general, it's better to have a separate documentation, but we can also add comments in the settings file directly!
