### ISSUE TITLE
Old docker image

### ISSUE THREAD

**Issue by nollm** [spiral-project/ihatemoney#1153]
In my docker-compose I use "ihatemoney/ihatemoney:latest" but portainer says the image is created at 2022-04-07.
Am I doing anything wrong or was no image pushed to the docker hub for along time?

**Comment by greedybro** [comment]
You can see when images have been built here -> https://hub.docker.com/r/ihatemoney/ihatemoney/tags

`Latest` and `5.2.0` are the same image and were pushed on 2022-04-07, `master` was built on 2023-02_18

If you want a newer image you can use the tag `master` instead of `latest`.
You can see the list of commits added to master since `5.2.0` here -> https://github.com/spiral-project/ihatemoney/compare/5.2.0...master

**Comment by nollm** [comment]
Thank you for the explanation!
