### ISSUE TITLE
"Internal Server Error" when trying to access admin dashboard

### ISSUE THREAD

**Issue by luporr** [spiral-project/ihatemoney#1195]
Environment: Ubuntu 22.04, installed I Hate Money (6.0.0) via Docker
Browsers: Firefox and Chrome

Hi, I just installed I Hate Money via Docker. I set the needed environment flags to enable the admin dashboard. I can get to the page where I have to input the password but no matter what I put, as soon as I submit the form I get an "Internal Server Error".

Any ideas what might cause this? I Hate Money otherwise works perfectly fine.

**Comment by Glandos** [comment]
Is it possible for you to provide the stack trace (or the complete log) from the server?

**Comment by Survolte** [comment]
Hello, I had the same problem. But that was because I didn't fully copy entierly  the return from the shell command (ihatemoney generate_password_hash).
On the log trace it was well indicated:
`/src/ihatemoney/run.py:118: UserWarning: The way Ihatemoney stores your ADMIN_PASSWORD has changed. You are using an unhashed ADMIN_PASSWORD, which is not supported anymore and won't let you access your admin endpoints. Please use the command 'ihatemoney generate_password_hash' to generate a proper password HASH and copy the output to the value of ADMIN_PASSWORD in your settings file.`

**Comment by luporr** [comment]
Sorry I never got back to provide log files. I did not have the capacity to do so back then.

Anyway, I freshly installed I Hate Money today and the password input seems to work in the sense that it throws an error and I cannot seem to get it to accept my password. I followed the procedure to properly hash it.

**Comment by zorun** [comment]
Closing, feel free to open again if you have more detailed informations (logs, traceback, etc)
