### ISSUE TITLE
Mobile web UX improvements

### ISSUE THREAD

**Issue by asavageiv** [spiral-project/ihatemoney#1263]
The current mobile web UX does not fit all in one screen width on my Pixel 7. It would be nice if the expense table could be condensed to fit on one screen. Splitwise does this well, so I've attached a screenshot.
It's mostly just layout changes. The main UX change is that tapping an expense opens the "edit" page and the "delete" button gets moved to the "edit" page.

Are you open to changes in this direction? We can discuss whether it's better to have a different layout on mobile screen widths or just modify the web UX to be more mobile friendly.

![ihatemoney](https://github.com/spiral-project/ihatemoney/assets/3028205/4c389245-651a-4ea2-9616-55e0971bb7a3)
![splitwise](https://github.com/spiral-project/ihatemoney/assets/3028205/ada1508b-7b86-4fd6-b29e-fbe8f323daaa)

**Comment by zorun** [comment]
Sure, improving the mobile UX is definitely in the scope of the project!

We already have a (slightly) different layout in the Statistics page for small screens, so we could imagine the same kind of things for the list of bills.

**Comment by Turtle6665** [comment]
Hello, 
I was planning on opening this discussion as I've been working on a mobile first approach front-end during the last month and a half. For now, I chose a random name for the project, and it's currently using the Rest-API as it's a full html/JS implementation. As you can see on the screenshots, the layout may also a bit too much inspired from the tricount app...

The view on mobile:
![image](https://github.com/spiral-project/ihatemoney/assets/110727570/bf4fdcbb-a4cd-46fe-8425-da64db663b96)

The view on desktop: 
![image](https://github.com/spiral-project/ihatemoney/assets/110727570/256aea52-2938-4fbb-b33c-ed6384f0c693)

You can try directly the demo hosted on the [GitHub page](https://turtle6665.github.io/BillBliss/dashboard.html?project=demo&token=WyJkZW1vIl0.GGWpACJMuleIMJj9HxbUrEDSSAc).
Anyway, if this is the direction that IHM want's to follow, I would be happy to help.

**Comment by zorun** [comment]
FYI, we recently clarified the current direction of the project: https://ihatemoney.readthedocs.io/en/latest/contributing.html#current-direction-as-of-2024

As such, @asavageiv , we are definitely welcoming UI/UX improvements, especially on mobile. The best way to go forward is to submit a pull request and screenshots and start a discussion there. I am closing this ticket because there's nothing actionable and the new position should make it clear to everybody that UI/UX improvements are always welcome.

@Turtle6665 your project looks very interesting, but at this point ihatemoney is aiming towards maintaining the existing code, not introducing such a major change (see the "current direction" link I posted above). That doesn't prevent you from working on this alternative frontend: it merely means that it won't be integrated in ihatemoney itself. FYI, there was an attempt to rewrite everything from scratch a few years ago, and I think it also went with decoupling the API and the front: https://github.com/spiral-project/elm-ihatemoney/
