### ISSUE TITLE
Use the ActivityPub protocol to federate usage across ihatemoney instances

### ISSUE THREAD

**Issue by stevenroose** [spiral-project/ihatemoney#1280]
I have been looking around for a self-hosted alternative for Splitwise, but as with any app that relies on some network effect, it's hard to self-host and not run into people needing accounts on different instances.

I think the model of ihatemoney is a bit more centered around projects and not people, but I think it would be a good contender to build something along the lines of a Splitwise alternative that is more centered around splitting bills between ad-hoc groups of friends meeting up. The ActivityPub protocol could be used to make sure that users on different instances can still split money together.

I think NLnet or FramaSoft could be enticed to provide a grant for a feature like this and maybe a crowdfunder could be started as well. There is quite a significant crowd on Mastodon that is interested in federating services and projects using the ActivityPub protocol.

This is another project in Python that uses the ActivityPub protocol: https://github.com/bookwyrm-social/bookwyrm

**Comment by almet** [comment]
Hey, that would be really cool :+1: We already offer an RSS feed (see #1130), so it's "easy" to get updates. Having something decentralized could be useful, but would require quite a bit of work in order to ensure all the parties have the same information. I can see how this could be useful though.

Using NLNet for this could make sense, and I don't believe Framasoft is offering grants (if they are, don't hesitate to share a link, I couldn't find one)

**Comment by zorun** [comment]
As you said, Ihatemoney has no user accounts, it's organized around "projects". It's very easy to invite people, simply share a link and they can start adding bills to the project. I believe it alleviates the concern about network effect. In fact this model even encourages deploying many self-hosted Ihatemoney instances: people are not locked into a single instance, they can easily create projects on another instance with no "cost" (i.e. without having to create accounts or validate an email)

As it stands, I don't quite see how useful ActivityPub support would be, or even how it could be implemented:

- who are the actors, since we don't manage user accounts?
- how would you manage trust and consistency between instances?

**Comment by zorun** [comment]
We recently clarified the current direction of the project: https://ihatemoney.readthedocs.io/en/latest/contributing.html#current-direction-as-of-2024

ActivityPub and federation across instances definitely doesn't fit the "simplicity" criteria, so I am closing this ticket.

By the way, somebody has developed an Android app that seems to implement "decentralised" expense management (I don't think it uses ActivityPub though, and it looks unmaintained): https://gitlab.com/flexw/splitbills
