### ISSUE TITLE
Display statistics as a graph

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#136]
It could be nice to have a summary tab with information about what everybody did pay and did spend as well as the total of expenses for the group.

**Comment by almet** [comment]
What would that look like?

**Comment by Natim** [comment]
![solde-demo](https://cloud.githubusercontent.com/assets/229453/12854164/5baa1206-cc38-11e5-8603-cba6a4a14ad7.png)

I was thinking of something like that.

**Comment by almet** [comment]
That's really cool! I think we could even provide this information [as a graph](https://wpoely86.github.io/D3.js-Diverging-Stacked-Bar-Chart/) (Diverging stacked bar chart)

**Comment by zorun** [comment]
Having a graph for statistics would be very nice, and probably not that hard to do, I can give it a try :)

I think this kind of simple line chart would be easier to read: http://www.chartjs.org/samples/latest/charts/line/basic.html
There would be one line for each participant, and one point per month showing the balance for the month.  There could be an option to show the cumulative balance instead of the "instantaneous" balance. The timescale could be changed by the user to display data by day, or week, or year.

One practical question though: would it be better to use the API with Ajax queries, or just write a view that generates the necessary data?
Generating javascript variables in a Jinja template (like [here](https://pythonspot.com/flask-and-great-looking-charts-using-chart-js/)) is simple but not very clean, while Ajax queries are cleaner but involve dealing with API authentication.

**Comment by Natim** [comment]
@zorun thank you for your message and welcome to this project.

I don't think the project already have a REST API, so if you were to build one, it would be a bit of work. (CORS, Auth, utilities, documentation).

Also it might be a interesting project to build one.

For now, I guess having a django rendered view would be good enough.
I also wish to have a table explaining how much money users spend.

I am usually using a project per trip (with family and friends) and I don't need the monthly feature but more a total of all the expenses.

Last time I also wanted some metrics about how much was spend for the car, how much for the accomodation and how much for food and tourism.

**Comment by zorun** [comment]
Hi @Natim 

There are already such statistics shown in a table, from #257 :) see for instance https://ihatemoney.org/demo/statistics

Regarding the API, I was thinking of using this one https://ihatemoney.readthedocs.io/en/latest/api.html

**Comment by almet** [comment]
@zorun we never actually answered you! I think the best way to go is to integrate the Javascript in a view to be served directly by the python app. While this method is subject to discussion, it's the way all the project is currently built, so we better stick with it for clarity :-)

If you want to work on this (or if anyone wants), don't hesitate, that would be a welcome addition! Cheers!

**Comment by indatwood** [comment]
It seems this feature is still looking for somebody to implement it :-)

**Comment by zorun** [comment]
Yes, I never went around to try something, feel free to pick this up :)

For now I'm producing graphs "offline" with a custom json-to-gnuplot conversion script, but it would definitely be better to have it integrated in IHM!

**Comment by CubixPro** [comment]
Can I work on this?

**Comment by Glandos** [comment]
@CubixPro yes, you can start working on this.
Don't hesitate to make a prototype first. We usually prefer solutions that are lightweight: not too much dependencies, and keep the page light on JS for example.
I know that nice charting needs JavaScript. But we don't need to provide a Grafana-like screen :)

**Comment by CubixPro** [comment]
Should I use Canvas.js?

**Comment by Glandos** [comment]
It seems that CanvasJS [requires a licence](https://canvasjs.com/license/). Google Charts requires [loading from Google servers](https://developers.google.com/chart/interactive/docs/basic_load_libs), so it's also a non-goal for this project.

However, there are a lot (too much?) other libraries that can fit. For example [C3.js](https://c3js.org/) that is based on D3. It's maybe missing some features but I don't think we need them. Or, if you find a missing use case, please tell us :)

For prototypes, you can simply start but sending screenshot in this thread. You can drag'n'drop images right in the comment text field, and GitHub will upload it for you.

**Comment by CubixPro** [comment]
Okay sure thanks. I'll look into this and let you know :)

**Comment by thejacobx** [comment]
Hi guys, is this still open? Can I work on this issue? :)

**Comment by Glandos** [comment]
I can't believe I waited so long to answer to you, @thejacobx. If you are still opened to contribution, you can start on it.
But be aware that we will accept a contribution with a compatible charting library. So, no external loading, a no non-free license :)

**Comment by mcflyhalf** [comment]
I am hoping that the 3rd time would be a charm with this issue and checking whether it is still available. I am willing to take it up.
Is this still open? Can I try to work on it?

**Comment by almet** [comment]
Play thanks ! Let us know if you need help ☺️

**Comment by almet** [comment]
Please, have a look at the existing PR at https://github.com/spiral-project/ihatemoney/pull/731. good stuff there, it was abandoned but you probably could build on top of it.

**Comment by CarlosPimentel10** [comment]
Hello Guys.

Sorry for not giving any feedback yet.

I was pretty tight on time working on 2 startup projects plus Google MWS
track and
a mobile internship. I am pretty much done with both study projects so I
was trying to tackle
the #736 graph stats issue.

I am not quite familiar with flask, so I forked the repo, cloned it and
installed
missing flask dependencies however I can't launch the app. I know is
probably something
very simple, the thing is I am good with ML and Statistics with scikit, and
so on but I want to see first how the api is working right now then I can,
make the additions in the models.py or
other files.

I am keen to tackle this one and keep learning

**Comment by almet** [comment]
Hey, cool to have you onboard :-) I can try helping you the best I can. Can you please post some information so I can try debug the situation? You could for instance put the error message here, and maybe a stacktrace?

Also, the best way to do this would be to open a new issue to help you getting started, in order to keep the history of this issue clear! Cheers.

**Comment by zorun** [comment]
A statistics page (as requested initially) has been added a long time ago.

There have been several attempts at adding graphs but none went through. Ihatemoney is currently very lightweight regarding javascript (I believe we only have javascript from bootstrap), and this is something we want to keep, see https://ihatemoney.readthedocs.io/en/latest/contributing.html#current-direction-as-of-2024

As mentioned by @Glandos in #1011, one way to go would be to use [pygal](https://www.pygal.org/en/stable/) and its [Flask integration](https://www.pygal.org/en/stable/documentation/output.html#flask-app).

I am closing this ticket because it is not a priority of the project, but a simple proposal using pygal and good UI/UX integration would definitely be considered for inclusion.
