### ISSUE TITLE
Remove dead code for archive creation

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#170]
While working on #168 I stumbled uppon the « create archive » feature, which seems to do nothing. 

It seems like something half-implemented ; should we remove that dead code from code base ?
@almet  ?

**Comment by almet** [comment]
Hey, I don't remember anything about this to be honest, so I would suggest you remove it, yes!

**Comment by JocelynDelalande** [comment]
So let's keep this issue open as a reminder :-)

**Comment by almet** [comment]
Yep! I updated the title.

**Comment by 0livd** [comment]
The thing here is that deleting the archive table in the database model is not as trivial as it seems. In the existing migration scripts, the constraint between the bill and the archive tables is created without a name (the name parameter for sa.ForeignKeyConstraint is optional) so a random name is automatically generated by the underlying database engine. The problem is that constraint alteration or deletion are only made by name so in this case it is impossible to create an alembic migration script that would automatically drop the constraint between the bill and archive tables. This would need to be done manually or by a tricky SQL script that would retrieve the name of the constraint ... I think the best option is just to delete all the code related to the archive feature but leave the database model as is
See http://alembic.zzzcomputing.com/en/latest/naming.html for more info

**Comment by almet** [comment]
For reference, here is the commit that introduced the archive feature: https://github.com/spiral-project/ihatemoney/commit/801802836a648ac0865c1c932e3cf9a01e3a639e

@0livd thanks for the investigation, and sorry to hear that this 6-years-younger myself did cause this trouble ;-) I guess what you're proposing is the way to go, at least until we come up with a better solution!
