### ISSUE TITLE
XSS vulnerability on list_bills

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#173]
It seems that someone happily & successfully tested a XSS on the list_bills view. See screenshot.

![xss](https://cloud.githubusercontent.com/assets/429633/22950310/6f03ceba-f305-11e6-8389-e8d7d9ca02f3.png)

I disabled the XSS-ing buddy and removed it from the bills where it was on the demo project to avoid bothering visitors, but the bug remains.

**Comment by aavenel** [comment]
The XSS seems to be caused by this line 
`        html.append(u'<p><label for="%s">%s<span>%s</span></label></p>'
            % (choice_id, '<input %s /> ' % html_params(**options), label))`

in _forms.py_

We should use template instead of writing html like this. I don't have time to fix this tonight so if somebody wants to submit a PR, you're welcome :)
PS : there is also some unescaped parameters on _list_bills_ template, don't know if it's exploitable though.
