### ISSUE TITLE
Move tests away from the budget directory

### ISSUE THREAD

**Issue by 0livd** [spiral-project/ihatemoney#196]
We should put the tests in a test directory so it's cleaner and more flexible e.g. having separate files for configuration tests, separate the tests in multiple files, ...
We won't be able to run the tests with python tests.py anymore because of import errors but unittest has a discovery module to handle such cases `python -m unittest discover` https://docs.python.org/2/library/unittest.html#test-discovery

**Comment by JocelynDelalande** [comment]
> We should put the tests in a test directory so it's cleaner and more flexible 

Why cleaner ? tests are part of the software, having them belonging to `budget.tests` seems the right way to me :-)


> e.g. having separate files for configuration tests, separate the tests in multiple files, ...

Good practices indeed. A *budget/tests* folder does the job also for that :)

**Comment by almet** [comment]
I actually quite agree that tests should be in a python folder rather than in a simple file.

That being said, I don't have any strong opinion about having them in or out the `budget` module itself. I know that we've been discussing this for the [pelican](https://github.com/getpelican/pelican) project at some point and decided to include the tests in the same python package to ease packaging (it seems to help for some linux distributions) but I don't remember the details.

I personally don't have any strong opinion on this, so either way would work. Pytest contributors [wrote some documentation about that](https://docs.pytest.org/en/latest/goodpractices.html), which might help us chose the best choice for us

**Comment by 0livd** [comment]
For me it makes more sense to put the tests outside the ``budget`` directory because they are not meant for the end user. According to the pytest doc, if we go this way we need to introduce a new ``src`` directory, so putting them in ``budget/test`` might just be easier

**Comment by almet** [comment]
I think we should go with `budget/test` here, as it might to run the tests for packagers of distributions like Arch linux (which encourage to run the tests at packaging time.)
