### ISSUE TITLE
After entering the admin password, I'm getting redirected to the homepage

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#310]
Everything is in the title.

**Comment by almet** [comment]
This seems to be because the code checks for `pbkdf2:sha256` while my generated password is `pbkdf2:sha1`. This is probably because some hash algorithms aren't available on my target platform.

Still, we should not enforce the use of a specific algorithm, especially if it makes us not support passwords generated with our own method.

**Comment by 0livd** [comment]
Hum...that's weird because this password check is only executed when the app is started and it only prints a warning.
There is a ``goto`` variable in the admin authentication logic which defaults to the home page and could explain your problem.
https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/web.py#L124
But yeah your fix is needed anyway :)
