### ISSUE TITLE
Full history of changes

### ISSUE THREAD

**Issue by Ambrevar** [spiral-project/ihatemoney#426]
Something that's always bugged me with shared budget managers is that there is no way to see if someone edited something unbeknownst to the other (possibly inadvertently).

This means that those systems lack reliability: when time comes to settle the bills, it's hard to be confident about the data.

A neat way to fix this would be to record _all edits_.  This way, anything fishy (such as "Entry foo deleted") would become apparent.

Thoughts?

**Comment by almet** [comment]
Hi, thanks for your message! 

I think that would be a welcome addition, but I personally don't have any use case for it.

It's interesting to note (and relevant to this topic) we don't really have a concept of users (everyone is the same user interacting with the system), so it's hard to track who made the changes (we could track IP addresses ?).

It's also important to keep in mind that Ihatemoney is a tool that solves 10% of the use cases for 90% of the users. Something easy to use for about everyone, which doesn't solve every use case, but does what it does well.

Said differently, If we add a log feature, it should not be too visible, as I think it's not something that would be useful to the majority of our users. We could add a link there somewhere in the project settings for instance?

Would you be willing to implement this? What do others contributors think about this?

**Comment by almet** [comment]
That makes sense :-) I'd say : let's do it!

**Comment by Andrew-Dickinson** [comment]
Hi @almet 

I'm looking into working on this issue. My plan is to add a database table specifically for handling this feature and then a logging call at each endpoint (and each API endpoint as well) which adds an entry to this table, recording the IP address of the request.

Then we can list the relevant log entries for each project on a page called "History" listed next to the "Settle", "Statistics", "Settings" links.

Does this approach sound like the right way of doing things?

**Comment by Glandos** [comment]
Please make IP recording optional.

Some administrators and users don't want this, and new privacy related laws make it even harder to deal with IP addresses. At least in UE, it is considered as a personal identifier.

**Comment by almet** [comment]
Hey, thanks for your proposal. I'm handing this to the new maintainers, I'll let you see with them!

**Comment by Andrew-Dickinson** [comment]
How about we add two options to the "Settings" page?
- [x] Enable Project History
  - [ ] Record IP Addresses

Where "Enable Project History" is turned on by default, but "Record IP Addresses" is off by default, and "Enable Project History" being off implies that "Record IP Addresses" is also off.

**Comment by Andrew-Dickinson** [comment]
It seems like the [SQLAlchemy-Continuum](https://sqlalchemy-continuum.readthedocs.io/en/latest/index.html) package could be really useful here. It can automatically log database changes (and IP addresses if used with the Flask plugin). 

One challenge I see is disabling IP address logging on a per-project basis. I'll keep digging to see if there's a way to intercept the database call and scrub the IP address if neccessary.

**Comment by indatwood** [comment]
I'm also -1 on using IP addresses, for the same reasons @glandos points out, but we could use a hash based on these IP addresses (so that it's unique, but it's not using a personal info such as the IP address), or maybe find another way to identify the user (but I don't know which other way we could use, as we don't have a concept of user !)

**Comment by Andrew-Dickinson** [comment]
**A note on hashing IP addresses**

IPv4 addresses are only 32 bits (IPv6 are 128bits). Since most internet users are still on IPv4 (and have limited control of it based on their ISP), from a privacy perspective let's limit the discussion to just IPv4 addresses for the moment.

Md5 hashes are 128 bits. Depending on the flavor, SHA hashes are 128, 256, or 512 bits. The point is that since IP addresses are fixed-length, there aren't enough of them to cause hash collisions and the hash can be [reverse engineered quite easily](https://security.stackexchange.com/questions/74113/do-i-have-to-hash-users-ip-addresses-when-i-log-them). Based on some [quick research](https://stackoverflow.com/questions/11000736/how-to-calculate-the-time-needed-to-calculate-a-sha-256-hash), it looks like a rainbow table for the entire IPv4 address space can be created in just a few minutes. 

Even if we did something like salting the hash with the project id, it's still only a few minutes per project for an attacker to reverse engineer all of the IP addresses logged for that project.

The stack overflow link above suggests that if it makes sense for our application we could use a keyed hash function, such as HMAC. However, the key would still need to be stored in plaintext on the IHM server in order for it to be useful, so this doesn't offer much protection.

We could solve the lack of collisions by truncating the output of an existing hash function to be less than 32 bits (we could have a special case for IPv6 addresses). Although it carries the risk of reporting two transactions as being from the same person when they're not (the result of a collision), and selecting how many bits to keep is a tricky balancing act between avoiding collisions and protecting privacy. Reverse engineering attacks may still be practical also. An attacker could still compute a rainbow table in the same amount of time, although they now have multiple possible IP addresses for each hash they obtain. We can vary how many IP addresses they have to check to identify the user by changing the number of bits we keep, but that will always have implications for the collision rate.

We could also consider a non cryptographic "hash function", where we only record information necessary to identify the source of the transaction. One example of this would be to do some sort of geo-lookup of the IP and record its location to a configurable specificity (e.g. only record the country of origin). However, for what seems to be a common user case (i.e. flatmates), this is unlikely to provide any transparency into the origin of the transaction.  

Another option to uniquely identify users without IP addresses would be some sort of browser fingerprinting. We could generate and store unique token on each connecting browser, or less directly try to profile the browser based on a [number of factors](https://en.wikipedia.org/wiki/Device_fingerprint#Browser_fingerprint). However, this seems just as invasive (if not more invasive) as tracking IP addresses. We've generated new PII in order to avoid tracking other PII.

To me this question circles back to establishing a threat model. Clearly defining why we are trying to obscure IP addresses, in addition to defining what information we need to retain on users in order to provide the desired transparency.

**Comment by Glandos** [comment]
I guess that we either try to record who did what, or just what was done.

If we want to really identify users, then we need to create an user account system. But it is clearly out of the scope of this project, so let's rule it out.

An history of what was done is clearly a nice improvement.

Who did what with IP addresses can be acceptable, just to be able to discriminate changes in small projects. Of course, we should be able to switch it on-off on a per project basis.
