### ISSUE TITLE
Split test into little ones.

### ISSUE THREAD

**Issue by JoseAntonioTorre** [spiral-project/ihatemoney#501]
I have been reading the code of test and I have seen that, for example, in test_project we are asserting different use cases. In my opinion, it is better to divide the test and refactor it in a little methods.

What is your opinion?
For example, instead of testing that first we can create a project, later we can not create the same, it is better to have a test to create a project, a test to test that we can not create a duplicated one, and so on.

**Comment by almet** [comment]
It's probably better to have atomic test functions, because it's easier to detect where the problem is when it arises. I believe this was done this way because it was easier at that time.

For me the main important thing is to have a coverage of all the scenarios. If you feel like splitting every scenario into multiple (atomic) tests, do not hesitate :-)

**Comment by JoseAntonioTorre** [comment]
I think that it is better, yes!, I will try to start working on it and let you know it!

**Comment by JvPy** [comment]
I would like to contribute.

Never worked with tests before, but would like to learn, if possible.

**Comment by almet** [comment]
@JoseAntonioTorre would you like to mentor @JvPy on this?

**Comment by JoseAntonioTorre** [comment]
Yes, I am not an expert in testing but I can try it!
@JvPy First, get used to read the testing code and try to figure out what is happening in each test. After that, you will probably see that there are tests that asserts several things that are not related to the test itself. The idea is to divide those tests in little ones in order to make it easier to check where are the errors (in case we have any error...)

**Comment by indatwood** [comment]
Hi @JoseAntonioTorre and @JvPy. Are you still happy to work on this?

**Comment by Villaquiranm** [comment]
@indatwood @Glandos  Hello, could you give more information about this issue like the most problematic files / test to refactor ?

Thanks

**Comment by Glandos** [comment]
Well @Villaquiranm I'm glad you asked. The few tests I've written were difficult, because it seems to me that a lot of code has to be duplicated, especially for project and bill creation.
The `BudgetTestCase` is clearly too big, and should at least be in its own file.

So as a start, it should be nice if each "real" test case class were in their own file. But it should be done with code factorization in mind, in order to avoid repeating a lot of code. For example, some datasets like bill could be gathered and available in each test (I've spotted the `"id": "raclette"` too many times :yum: )

**Comment by Villaquiranm** [comment]
@Glandos Ok, i will try to do something nice :)

**Comment by Villaquiranm** [comment]
Hello @Glandos , I expect this PR is more or less what you expected, if you have any suggestion to improve it please let me know i'll be glad to continue coding
