### ISSUE TITLE
Add ability to record expenses in different currencies

### ISSUE THREAD

**Issue by ArthurG** [spiral-project/ihatemoney#512]
Consider the use case when a group of friends travels to a different country. They will likely have some expenses in their home currency (airplane, uber to airport, etc) as well as some expenses in the foreign currency (food, entertainment). 

This would be a really useful feature to add!

**Comment by skyrl69** [comment]
+1 to this feature. Last year we used 9 currencies on our august 
holidays, this year the same.
Having an automatic [xe.com] conversion is one thing for debt balance, 
but keeping both amounts is useful to input & check bills.

Nice to follow you for the last two months, guys ^

Charles+++

Le 25/11/2019 à 11:22, Arthur Guo a écrit :

**Comment by almet** [comment]
Hi, thanks for taking the time to open an issue for this.

I've been thinking a bit and… I'm not sure we want this. It seems at a first glance out of scope for IHM, and will probably create more problems than it would solve : how should we handle the conversion rate ? In which currency should we compute the balances?

One simple way to solve this would be to have a default currency per project, and then have a tool to do the conversion *when we enter the new bill*, so that it converts from one currency to another one. Then everything is stored in one currency.

We could detect the currency quite easily using their text reprentation (EUR, USD, etc), which would make this an advanced use case.

This approach seems a bit overcomplicated for the scope of this very small project : it will tie IHM to another external lib / API, and it means we'll need to maintain it in the long term.

For the record, here are a few libs that might help : 
- https://pypi.org/project/CurrencyConverter/ seems to do the conversion from a database (not sure it works well from day to day changes, in which case we would need to use an API of some sort)
- here is a link to an API : https://www.exchangerate-api.com/docs/python-currency-api
- https://pypi.org/project/currencies/ seems to do the display properly (but I'm not even sure we need this)

If somebody want to take it, I'll be happy to review the code for this. Also, feedback from other users / dev is welcome :-)

**Comment by ndkoch** [comment]
If nobody else has taken this up, I am just beginning to contribute and would like to try and take this on.

**Comment by almet** [comment]
@ndkoch feel free to hack something up! As I said, I'm not sure how this should be done and depending on how it's done, it'll potentially not be merged if it makes things too complicated.

Not to discourage you, so if you feel like taking it, go ahead :-)

**Comment by ArthurG** [comment]
Another way you could do this is to :

- Record expenses in any currency
- At settle time, the user can:
1) See how the settlement would work if they were to pay in the original payment currency
2) Allow the user to select a currency, and then calculate settlement into the currency. 

For V1, it would probably be enough just to run the settlement algorithm on every currency, without tying into some currency conversion API.

**Comment by ndkoch** [comment]
#516

**Comment by 35609902357** [comment]
@almet @ndkoch [TrickyTripper](https://github.com/koelleChristian/trickytripper) has this feature, but the conversion rate has to be input manually. It would be useful to have it integrated with online conversion like [Currecncy](https://github.com/billthefarmer/currency) does, it fetches rates online and if no connection is possible it uses the last fetched rate.

**Comment by Natim** [comment]
What we usually do is what @35609902357 said, we keep track of the daily currency rate via a cronjob that fetches it everyday and then we use the rate of the day to convert everything to USD and then we display the total in the user currency.

**Comment by Glandos** [comment]
Thanks @ndkoch for your initial work on this. @dark0dave took it through the end.
