### ISSUE TITLE
Should we change the project's license?

### ISSUE THREAD

**Issue by comradekingu** [spiral-project/ihatemoney#519]
Continued discussion from https://github.com/spiral-project/ihatemoney/issues/517

@arnaudbos That is a good principle. What makes this Beerware-ish license superfluous to what is already an addition to the BSD-license boils down to whether beverages have any place in a license file.
I know a little bit about licenses, and I still felt unsure about what the license was. Didn't see the readme at first. The heart of the matter holds true for BSD too, to me the idea of building community around something which can fail it, at the point of failure (detailed above), is to me a step short of "YAGNI" minimalism.
[Longer musing](https://github.com/liberapay/liberapay.com/issues/564#issuecomment-565339354) on the community aspects of license minimalism.

It is my impression nobody ever complained about code not being forked away into a closed effort. It is nice to have some recourse if that is to happen, and it seems to rarely happen with GPL2/3 code for this reason.
AGPL further protects the network aspect.

Licensing and communicating it is important to me, if the user doesn't know, then the experience is sold short of what it actually is, and should be, and appears to be in the ranks of many a project I don't want anything to do with. The impetus here being on the prevalence seeing precisely data regarding who buys what and when stolen, and maybe even expecting it.

**Comment by almet** [comment]
Thanks @comradekingu for creating this issue.

I'm personally OK with a license change to GPL, and even more to AGPL. The BSD beerware derivative was used because it though it was fun, but nobody actually offered me any beer ;-)

If we were to change the licensing, it's not clear what the steps would be : should we contact all contributors and ask for their agreement? (and what if we don't manage to get to them?)

**Comment by comradekingu** [comment]
The BSD points can be converted directly. (To the earlier point of you can take them anywhere without asking anyone) "Some rights reserved" and that point about beer potentially detracts from that. Beerware is a license, and it deepens how it differs. The FSF and OSI has flowcharts on compatibility. Would be nice to ask all contributors anyhow, even for the courtesy of doing so alone.

**Comment by aavenel** [comment]
Beerware licence is fun, but I agree that switching to a real BSD would be easier for new contributors and the change seems straightforward.

As for switching to an GPL/AGPL licence, this seems more complicated. I have not a strong opinion on this, but I don't really see why we should bother. I would have been perfectly happy with this licence at start, but I don't see any real benefit for it now.

Protection against forked code in a closed project is a valuable argument. However, there is already several private companies that offer service similar to ihatemoney, and usually in a more complete product.
Even if a company fork ihatemoney code and does not redistribute it, I'm not sure we will miss much. They will probably add features like Paypal integration or advertising, and this is not something that we really want :)

**Comment by almet** [comment]
I prefer the idea of a viral license in general rather than a more liberal approach.

@aavenel, Your current statement about the fact that IHM is less complete is correct today, but we  We don't know what IHM will become in the future. Making it difficult for people who would like to copy our features without contributing back is something worth it in my opinion.

So, if we are to change the license, I would prefer to go with a license that matches more with my political point of view, and that would be GPL.

The fact that it's more complicated shouldn't be an argument here for the license selection, IMHO : if it's **too** complicated, then we can still fallback to a more liberal BSD license.

**Comment by Glandos** [comment]
Here is my own point of view.

1. The BSD+beer is pointless but fun.
2. Switching to simple BSD could be done without formally asking anyone.
3. Switching to GPL/AGPL should be done with formal consent from contributors.

Personnally I think that BSD licensing is good enough for small projects without commercial competition. This project is in the middle, as said before, since some companies offers this as a commercial service (free with ads is commercial). But I don't think this is a real threat.
In the end, switching to GPLv3 seems a bit useless, since it is a web service. We should use AGPL or stick to BSD/MIT.

I have no clear thoughts on that switch, but I'll follow the leader :)

**Comment by almet** [comment]
I believe i should actually step back on this decision :-) If BSD is simple enough, then why not!

**Comment by comradekingu** [comment]
@aavenel No reason Ihatemoney should always be relegated to being worse or otherwise non-commercial. PayPal and advertisement can be added regardless. Some licenses are more complicated because they offer more protection. Any BSD offers zero protection against hardware encryption "tivoization", for example. Since none of the protections are potentially off the table, it is a good safeguard to have a defence against them. It is my opinion that these things are bad when they happen.

At the very base of which is seeing "as-a-service" model software taken to marketshare competition.
This is a critique forwarded here https://github.com/spiral-project/ihatemoney/issues/517#issuecomment-566553308

@Glandos Why do you think switching to one _needs_ formal consent over the other. Both of them don't have the beer clause, which is the only problematic one. It is a decision only for future contributions, the existing codebase could be forked to anything possible, or anything current contributors agree to.

---

I think it boils down to network software needing potentially network protections (AGPLv3+ or similar), and the license to do it is longer than the license that has the fewest protections. (BSD two clause)

**Comment by Glandos** [comment]
> Why do you think switching to one needs formal consent over the other.

It was just a matter of being honest to every past contributor :) Maybe a simple notification would fit.

**Comment by JohnReedLOL** [comment]
I like common licenses because when I do a GitHub advanced search I sometimes filter projects by license and typically I filter out anything other than MIT or Apache 2.0.

**Comment by indatwood** [comment]
Hey, so what should we do about this? It seems to be a political choice! (A)GPL seems to be the "best" choice, and BSD seems to be the "easy" one.

I believe having a lawyer's opinion about all this would help. I'm wondering if the FSF could help us with this?
