### ISSUE TITLE
Drop support of MySQL and replace it with MariaDB

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#743]
So I'm wondering if we should drop support for MySQL in favor of MariaDB. MariaDB is now the default mysql implementation on Debian 10, and since Debian 9.

Since we're about to release a major version of IHM, it should make sense to drop MySQL altogether as we now have a good community-driven replacement, which also solves some bugs (#632 ) for us :-)

What do you think?

**Comment by Natim** [comment]
I'm not sure what you mean by dropping support. In my opinion MariaDB and MySQL may use the same driver, don't they?

**Comment by Natim** [comment]
Actually this might be related to https://github.com/spiral-project/ihatemoney/issues/632#issuecomment-817342784
I'm ok with dropping support then.

**Comment by almet** [comment]
Yes, it's why I'm thinking about dropping support. In general, I don't think having a too wide support scope is a good idea.

**Comment by Glandos** [comment]
I'm no longer a real user of MySQL/MariaDB, but yes, all major Linux distributions switched to MariaDB. So, yes, support only MariaDB is a good option for me too.

**Comment by zorun** [comment]
I updated #631 to run the CI against mariadb, and I can confirm that mariadb 10.3.X passes all the tests.

So, I'm OK with dropping support for MySQL and requiring MariaDB >= 10.3.2. Debian buster satisfies this requirement; Debian stretch does not, but it is no longer supported anyway (because we stopped supporting Python 3.5)

I will prepare a PR to update documentation & release notes about this.
