### ISSUE TITLE
Allow entering time in date picker

### ISSUE THREAD

**Issue by rugk** [spiral-project/ihatemoney#888]
In contrast to the app (at least when used with Nextcloud Cospend), I cannot enter a time in this web application.

IMHO, it should be optional as sometimes you don't know a time, but well :sweat_smile: 

cf. https://github.com/spiral-project/ihatemoney/issues/887 -> it only shows a date field.

**Comment by rugk** [comment]
> Do you really need such fine-grained timing for your expenses?

TBH I really only opened it because the other apps, as already said (cospend etc.) do have that fine-grained granularity. I guess for them it is useful if you "just now" enter the time and so the current time is the valid one – that's easy to enter. Actually [I asked them to make it optional](https://github.com/eneiluj/cospend-nc/issues/96) as [otherwise that could be quite annoying](https://gitlab.com/eneiluj/moneybuster/-/issues/86) when you do not remember what time you've bought sth.
So to change the sorting (via time) and fix potential issues there, this may be useful.

**Comment by almet** [comment]
Hi @rugk, thanks for coming by and for taking the time to open issues. It's appreciated.

In IHM, we try to not include extra features when they do not add real value to the product. We chose to do this in order to have a cleaner codebase and reduce the time maintaining the project. I believe what you are requesting here is one of these use cases. It might be nice to have but in the end it will not really change how the product works or improve the user experience of the users.

Because of this, I'm closing your issue. If you feel frustrated about that, or if you really think we should allow entering time in the datepickers, then don't hesitate to reopen this issue and discuss it further.

Cheers, Alex
