### ISSUE TITLE
Where to put TLS certs?

### ISSUE THREAD

**Issue by Rick-W-Storm** [spiral-project/ihatemoney#960]
Where is the program expecting the certs required for HTTPS?
Apparently it's not using Apache/Nginx/lighttp or any other server supported by certbot. Not sure if this has been asked before but wiki and readme don't give any input on how to HTTPS this

**Comment by almet** [comment]
Hi, thanks for opening an issue about this.

In order to run with HTTPS, you need to put a reverse proxy in front of the application. How to do so [is documented here](https://ihatemoney.readthedocs.io/en/latest/installation.html#configure-a-reverse-proxy).

If you want to use `certbot`, you can use for instance nginx and then integrate the SSL certs automatically. I'm closing this issue as it's not really related to ihatemoney by itself, but feel free to comment if you need more help.

Cheers.
