### ISSUE TITLE
Docker latest and master: admin-dashboard only reachable under localhost and with reverse proxy CSRF-Error

### ISSUE THREAD

**Issue by AlexanderSch90** [spiral-project/ihatemoney#979]
see #977 
CSRF-Error happens in a local environment and is not an issue when online (with reverse proxy)
Accessing from localhost seems to not throw that CSRF error, whereas accessing from local IP 192.168.X.X throws

**Comment by zorun** [comment]
Can you be more specific about that CSRF error you are facing?

I believe this is just because of secure cookies, see this setting: https://ihatemoney.readthedocs.io/en/latest/configuration.html#session-cookie-secure
We decided to enable it by default, see this thread for more details: https://github.com/spiral-project/ihatemoney/pull/845#issuecomment-939513750

Is it an error you are facing in production, or just when testing locally?

Some couple of ideas on how to move forward:

- desactivate secure cookie when run in Docker (I'm definitely not a fan of this "solution")
- better document this setting in the docker-related doc, e.g. here: https://ihatemoney.readthedocs.io/en/latest/installation.html#with-docker

**Comment by AlexanderSch90** [comment]
@zorun: You are right! 
I think your solution of a better documention of this setting in the docker-related doc is good, e.g. here: https://ihatemoney.readthedocs.io/en/latest/installation.html#with-docker
